//import { Html } from "next/document"
import Navbar from '@/components/Navbar'
import { Roboto } from 'next/font/google'
import { Oswald } from 'next/font/google'
import "./globals.css"
export const metadata = {
    title: 'miApp :)',
    description: 'Generated by Next.js'
}

const roboto = Roboto({
    weight: ["300","400","500","700"],
    stylesP: ["italic","normal"],
    subsets: ["latin"],
})

const oswald = Oswald({
    weight: ["300","400","500","700"],
    stylesP: ["italic","normal"],
    subsets: ["latin"],
})
export default function RootLayout ({children}) {
    return (
        <html lang="en">
            <body className={roboto.className}>
            <Navbar/>
            {children}
            </body>
        </html>
    )
}