
import Users from "@/components/Users"

export const metadata = {
    title: 'mi pagina especial home ',
    description: 'Generated by Next.js'
}
 function HomePage() {
    return <section>
    <h1>Home Page</h1>
    <Users></Users>
    
    </section>
}

export default HomePage